server:
  port: 9226

spring:
  application:
    name: Config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitvermacist/config-server
          clone-on-start: true